#ifndef RULE_ERROR_H
#define RULE_ERROR_H
#include "RuleApi.h"

typedef enum
{
	E_ERR_RULE_SUCCESS = 0x00030000,
	E_ERR_RULE_ADD_DUPLICATE_ID,
	E_ERR_RULE_ADD_INVALID_ID,
	E_ERR_RULE_MOD_EMPTY_ID,
	E_ERR_RULE_MOD_INVALID_ID,
	E_ERR_RULE_DEL_EMPTY_ID,
	E_ERR_RULE_DEL_INVALID_ID,
	E_ERR_RULE_PARAM_ERROR,

	E_ERR_SCR_OP_ADD_DUPLICATE_ID,
	E_ERR_SCR_OP_ADD_INVALID_ID,
	E_ERR_SCR_OP_MOD_EMPTY_ID,
	E_ERR_SCR_OP_MOD_INVALID_ID,
	E_ERR_SCR_OP_DEL_EMPTY_ID,
	E_ERR_SCR_OP_DEL_INVALID_ID,
	E_ERR_SCR_OP_PARAM_ERROR,

	E_ERR_SCR_OPS_ADD_DUPLICATE_ID,
	E_ERR_SCR_OPS_ADD_INVALID_ID,
	E_ERR_SCR_OPS_MOD_EMPTY_ID,
	E_ERR_SCR_OPS_MOD_INVALID_ID,
	E_ERR_SCR_OPS_DEL_EMPTY_ID,
	E_ERR_SCR_OPS_DEL_INVALID_ID,
	E_ERR_SCR_OPS_PARAM_ERROR,

	E_ERR_SCR_ACT_ADD_DUPLICATE_ID,
	E_ERR_SCR_ACT_ADD_INVALID_ID,
	E_ERR_SCR_ACT_MOD_EMPTY_ID,
	E_ERR_SCR_ACT_MOD_INVALID_ID,
	E_ERR_SCR_ACT_DEL_EMPTY_ID,
	E_ERR_SCR_ACT_DEL_INVALID_ID,
	E_ERR_SCR_ACT_PARAM_ERROR,
	
	E_ERR_RTE_OP_ADD_DUPLICATE_ID,
	E_ERR_RTE_OP_ADD_INVALID_ID,
	E_ERR_RTE_OP_MOD_EMPTY_ID,
	E_ERR_RTE_OP_MOD_INVALID_ID,
	E_ERR_RTE_OP_DEL_EMPTY_ID,
	E_ERR_RTE_OP_DEL_INVALID_ID,
	E_ERR_RTE_OP_PARAM_ERROR,

	E_ERR_FILTER_OP_ADD_DUPLICATE_ID,
	E_ERR_FILTER_OP_ADD_INVALID_ID,
	E_ERR_FILTER_OP_MOD_EMPTY_ID,
	E_ERR_FILTER_OP_MOD_INVALID_ID,
	E_ERR_FILTER_OP_DEL_EMPTY_ID,
	E_ERR_FILTER_OP_DEL_INVALID_ID,
	E_ERR_FILTER_OP_PARAM_ERROR,

	E_ERR_FILTER_OPS_ADD_DUPLICATE_ID,
	E_ERR_FILTER_OPS_ADD_INVALID_ID,
	E_ERR_FILTER_OPS_MOD_EMPTY_ID,
	E_ERR_FILTER_OPS_MOD_INVALID_ID,
	E_ERR_FILTER_OPS_DEL_EMPTY_ID,
	E_ERR_FILTER_OPS_DEL_INVALID_ID,
	E_ERR_FILTER_OPS_PARAM_ERROR,
	
	E_ERR_FILTER_ACT_ADD_DUPLICATE_ID,
	E_ERR_FILTER_ACT_ADD_INVALID_ID,
	E_ERR_FILTER_ACT_MOD_EMPTY_ID,
	E_ERR_FILTER_ACT_MOD_INVALID_ID,
	E_ERR_FILTER_ACT_DEL_EMPTY_ID,
	E_ERR_FILTER_ACT_DEL_INVALID_ID,
	E_ERR_FILTER_ACT_PARAM_ERROR
}ERuleError_t;

inline const char * fnRuleApiStringRuleError(ERuleError_t _eT)
{
	switch(_eT)
	{
		case E_ERR_RULE_SUCCESS                  :   return "E_ERR_RULE_SUCCESS";       
		case E_ERR_RULE_ADD_DUPLICATE_ID         :   return "E_ERR_RULE_ADD_DUPLICATE_ID";
		case E_ERR_RULE_ADD_INVALID_ID           :   return "E_ERR_RULE_ADD_INVALID_ID";
		case E_ERR_RULE_MOD_EMPTY_ID             :   return "E_ERR_RULE_MOD_EMPTY_ID";
		case E_ERR_RULE_MOD_INVALID_ID           :   return "E_ERR_RULE_MOD_INVALID_ID";
		case E_ERR_RULE_DEL_EMPTY_ID             :   return "E_ERR_RULE_DEL_EMPTY_ID";
		case E_ERR_RULE_DEL_INVALID_ID           :   return "E_ERR_RULE_DEL_INVALID_ID";
		case E_ERR_RULE_PARAM_ERROR              :   return "E_ERR_RULE_PARAM_ERROR";
		case E_ERR_SCR_OP_ADD_DUPLICATE_ID       :   return "E_ERR_SCR_OP_ADD_DUPLICATE_ID";
		case E_ERR_SCR_OP_ADD_INVALID_ID         :   return "E_ERR_SCR_OP_ADD_INVALID_ID";
		case E_ERR_SCR_OP_MOD_EMPTY_ID           :   return "E_ERR_SCR_OP_MOD_EMPTY_ID";
		case E_ERR_SCR_OP_MOD_INVALID_ID         :   return "E_ERR_SCR_OP_MOD_INVALID_ID";
		case E_ERR_SCR_OP_DEL_EMPTY_ID           :   return "E_ERR_SCR_OP_DEL_EMPTY_ID";
		case E_ERR_SCR_OP_DEL_INVALID_ID         :   return "E_ERR_SCR_OP_DEL_INVALID_ID";
		case E_ERR_SCR_OP_PARAM_ERROR            :   return "E_ERR_SCR_OP_PARAM_ERROR";
		case E_ERR_SCR_OPS_ADD_DUPLICATE_ID      :   return "E_ERR_SCR_OPS_ADD_DUPLICATE_ID";
		case E_ERR_SCR_OPS_ADD_INVALID_ID        :   return "E_ERR_SCR_OPS_ADD_INVALID_ID";
		case E_ERR_SCR_OPS_MOD_EMPTY_ID          :   return "E_ERR_SCR_OPS_MOD_EMPTY_ID";
		case E_ERR_SCR_OPS_MOD_INVALID_ID        :   return "E_ERR_SCR_OPS_MOD_INVALID_ID";
		case E_ERR_SCR_OPS_DEL_EMPTY_ID          :   return "E_ERR_SCR_OPS_DEL_EMPTY_ID";
		case E_ERR_SCR_OPS_DEL_INVALID_ID        :   return "E_ERR_SCR_OPS_DEL_INVALID_ID";
		case E_ERR_SCR_OPS_PARAM_ERROR           :   return "E_ERR_SCR_OPS_PARAM_ERROR";
		case E_ERR_SCR_ACT_ADD_DUPLICATE_ID      :   return "E_ERR_SCR_ACT_ADD_DUPLICATE_ID";
		case E_ERR_SCR_ACT_ADD_INVALID_ID        :   return "E_ERR_SCR_ACT_ADD_INVALID_ID";
		case E_ERR_SCR_ACT_MOD_EMPTY_ID          :   return "E_ERR_SCR_ACT_MOD_EMPTY_ID";
		case E_ERR_SCR_ACT_MOD_INVALID_ID        :   return "E_ERR_SCR_ACT_MOD_INVALID_ID";
		case E_ERR_SCR_ACT_DEL_EMPTY_ID          :   return "E_ERR_SCR_ACT_DEL_EMPTY_ID";
		case E_ERR_SCR_ACT_DEL_INVALID_ID        :   return "E_ERR_SCR_ACT_DEL_INVALID_ID";
		case E_ERR_SCR_ACT_PARAM_ERROR           :   return "E_ERR_SCR_ACT_PARAM_ERROR";
		case E_ERR_RTE_OP_ADD_DUPLICATE_ID       :   return "E_ERR_RTE_OP_ADD_DUPLICATE_ID";
		case E_ERR_RTE_OP_ADD_INVALID_ID         :   return "E_ERR_RTE_OP_ADD_INVALID_ID";
		case E_ERR_RTE_OP_MOD_EMPTY_ID           :   return "E_ERR_RTE_OP_MOD_EMPTY_ID";
		case E_ERR_RTE_OP_MOD_INVALID_ID         :   return "E_ERR_RTE_OP_MOD_INVALID_ID";
		case E_ERR_RTE_OP_DEL_EMPTY_ID           :   return "E_ERR_RTE_OP_DEL_EMPTY_ID";
		case E_ERR_RTE_OP_DEL_INVALID_ID         :   return "E_ERR_RTE_OP_DEL_INVALID_ID";
		case E_ERR_RTE_OP_PARAM_ERROR            :   return "E_ERR_RTE_OP_PARAM_ERROR";
		case E_ERR_FILTER_OP_ADD_DUPLICATE_ID    :   return "E_ERR_FILTER_OP_ADD_DUPLICATE_ID";
		case E_ERR_FILTER_OP_ADD_INVALID_ID      :   return "E_ERR_FILTER_OP_ADD_INVALID_ID";
		case E_ERR_FILTER_OP_MOD_EMPTY_ID        :   return "E_ERR_FILTER_OP_MOD_EMPTY_ID";
		case E_ERR_FILTER_OP_MOD_INVALID_ID      :   return "E_ERR_FILTER_OP_MOD_INVALID_ID";
		case E_ERR_FILTER_OP_DEL_EMPTY_ID        :   return "E_ERR_FILTER_OP_DEL_EMPTY_ID";
		case E_ERR_FILTER_OP_DEL_INVALID_ID      :   return "E_ERR_FILTER_OP_DEL_INVALID_ID";
		case E_ERR_FILTER_OP_PARAM_ERROR         :   return "E_ERR_FILTER_OP_PARAM_ERROR";
		case E_ERR_FILTER_OPS_ADD_DUPLICATE_ID   :   return "E_ERR_FILTER_OPS_ADD_DUPLICATE_ID";
		case E_ERR_FILTER_OPS_ADD_INVALID_ID     :   return "E_ERR_FILTER_OPS_ADD_INVALID_ID";
		case E_ERR_FILTER_OPS_MOD_EMPTY_ID       :   return "E_ERR_FILTER_OPS_MOD_EMPTY_ID";
		case E_ERR_FILTER_OPS_MOD_INVALID_ID     :   return "E_ERR_FILTER_OPS_MOD_INVALID_ID";
		case E_ERR_FILTER_OPS_DEL_EMPTY_ID       :   return "E_ERR_FILTER_OPS_DEL_EMPTY_ID";
		case E_ERR_FILTER_OPS_DEL_INVALID_ID     :   return "E_ERR_FILTER_OPS_DEL_INVALID_ID";
		case E_ERR_FILTER_OPS_PARAM_ERROR        :   return "E_ERR_FILTER_OPS_PARAM_ERROR";
		case E_ERR_FILTER_ACT_ADD_DUPLICATE_ID   :   return "E_ERR_FILTER_ACT_ADD_DUPLICATE_ID";
		case E_ERR_FILTER_ACT_ADD_INVALID_ID     :   return "E_ERR_FILTER_ACT_ADD_INVALID_ID";
		case E_ERR_FILTER_ACT_MOD_EMPTY_ID       :   return "E_ERR_FILTER_ACT_MOD_EMPTY_ID";
		case E_ERR_FILTER_ACT_MOD_INVALID_ID     :   return "E_ERR_FILTER_ACT_MOD_INVALID_ID";
		case E_ERR_FILTER_ACT_DEL_EMPTY_ID       :   return "E_ERR_FILTER_ACT_DEL_EMPTY_ID";
		case E_ERR_FILTER_ACT_DEL_INVALID_ID     :   return "E_ERR_FILTER_ACT_DEL_INVALID_ID";
		case E_ERR_FILTER_ACT_PARAM_ERROR        :   return "E_ERR_FILTER_ACT_PARAM_ERROR";
		default: return "Unknown RuleError";
	};
	return "Unknown RuleError";
}

#endif
